<a href="https://colab.research.google.com/github/shachimaurya23/Learning/blob/main/Pytorch_learning_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import torch.optim as optim

## Load Dataset

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [3]:
df.drop(columns=["id","Unnamed: 32"],axis=1,inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train-Test Split

In [4]:
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Standardize the data

In [5]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [9]:
X_train

array([[ 1.08811738, -2.01336982,  1.25261162, ...,  2.29076172,
         2.63020833,  1.95723816],
       [-0.19529978, -0.50868424, -0.25510605, ..., -0.65817249,
        -0.25948136, -0.42884313],
       [-0.34629003, -1.3400402 , -0.36256931, ...,  0.03000767,
        -0.81722255,  0.10896674],
       ...,
       [-0.13378523,  0.92958446, -0.18602252, ..., -0.62996962,
        -0.41328743, -0.77722872],
       [-1.33248008,  0.63414392, -1.32448672, ..., -1.32523821,
        -0.73488193, -0.53352497],
       [ 1.70046675,  0.08448709,  1.69700858, ...,  1.56532963,
         0.19261525, -0.15578415]])

In [6]:
encode=LabelEncoder()
y_train=encode.fit_transform(y_train)
y_test=encode.fit_transform(y_test)

In [11]:
y_test

array([0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0])

## Numpy array to tensors

In [11]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

# Training using model from scratch without NN module

##Defining the model

In [12]:
class SimpleNN(): # single neuron NN from scratch
  def __init__(self,X):
    self.weights=torch.rand(X_train.shape[1],1,dtype=torch.float64,requires_grad=True) #creates a neoron with size 30X1

    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True) #as single neuron only 1 size of bias

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y): # as classification model we will use binary cross entropy loss
    #clamp Prediction to avoid log(0)
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [13]:
learning_rate=0.1
epochs=50

##Training Pipeline

In [14]:
model=SimpleNN(X_train)
model.weights

#define loop
for epoch in range (epochs):

  #foraward pass
  y_pred=model.forward(X_train_tensor)

  #loss
  loss=model.loss_function(y_pred,y_train_tensor)

  #backaward Pass
  loss.backward()

  #update paramenters
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #zero grad for new epoch
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 4.204590648628291
Epoch: 2, Loss: 4.108758290299111
Epoch: 3, Loss: 4.009184167832858
Epoch: 4, Loss: 3.9030744368320427
Epoch: 5, Loss: 3.793906490032251
Epoch: 6, Loss: 3.6824734276587283
Epoch: 7, Loss: 3.567869026166057
Epoch: 8, Loss: 3.4497131803234073
Epoch: 9, Loss: 3.3294507858655797
Epoch: 10, Loss: 3.1999056828289874
Epoch: 11, Loss: 3.0646342671562925
Epoch: 12, Loss: 2.9273742204998907
Epoch: 13, Loss: 2.7884531085984174
Epoch: 14, Loss: 2.6422617113055566
Epoch: 15, Loss: 2.491620559552449
Epoch: 16, Loss: 2.3326132482026694
Epoch: 17, Loss: 2.1740222008481203
Epoch: 18, Loss: 2.015251662654151
Epoch: 19, Loss: 1.860933969011995
Epoch: 20, Loss: 1.711919731136977
Epoch: 21, Loss: 1.5718450728484985
Epoch: 22, Loss: 1.4360610866982118
Epoch: 23, Loss: 1.3135429987293301
Epoch: 24, Loss: 1.2037419099691142
Epoch: 25, Loss: 1.1049233793425544
Epoch: 26, Loss: 1.0235323978934507
Epoch: 27, Loss: 0.9589147609774984
Epoch: 28, Loss: 0.9092889321632934
Epoch: 29,

In [15]:
model.bias

tensor([-0.2681], dtype=torch.float64, requires_grad=True)

In [16]:
model.weights

tensor([[-0.1777],
        [ 0.0503],
        [-0.0292],
        [ 0.3880],
        [ 0.2977],
        [-0.2517],
        [-0.2792],
        [-0.0704],
        [ 0.0303],
        [ 0.4724],
        [ 0.2355],
        [-0.1849],
        [ 0.1766],
        [ 0.1347],
        [ 0.1224],
        [-0.2274],
        [ 0.0953],
        [ 0.0687],
        [-0.1765],
        [ 0.0695],
        [ 0.0491],
        [ 0.1282],
        [ 0.1721],
        [-0.2810],
        [-0.4278],
        [-0.5045],
        [ 0.2360],
        [ 0.0195],
        [ 0.0431],
        [ 0.2318]], dtype=torch.float64, requires_grad=True)

##Evaluation

In [17]:
#model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5490920543670654


# NN Module Basic

In [2]:
import torch
import torch.nn as nn

In [2]:
# class NNModel(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()  # to initialize nn.Module class constructor
#     self.linear=nn.Linear(num_features,1)
#     self.sigmoid=nn.Sigmoid()

#   def forward(self,features):
#     out=self.linear(features)
#     out=self.sigmoid(out)


In [5]:
# class NNModel(nn.Module):
#   def __init__(self,num_features):
#     super().__init__()  # to initialize nn.Module class constructor

#     self.linear=nn.Linear(num_features,3)
#     self.relu=nn.ReLU()
#     self.linear2=nn.Linear(3,1)
#     self.sigmoid=nn.Sigmoid()

#   def forward(self,features):
#     out=self.linear(features)
#     out=self.relu(out)
#     out=self.linear2(out)
#     out=self.sigmoid(out)
#     return out

In [12]:
class NNModel(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [13]:
#create sample dataset
features=torch.rand(10,5)
model=NNModel(features.shape[1])
# call forwards pass
model(features)

tensor([[0.3953],
        [0.3910],
        [0.3945],
        [0.3920],
        [0.3912],
        [0.3945],
        [0.3958],
        [0.3893],
        [0.3910],
        [0.3859]], grad_fn=<SigmoidBackward0>)

In [15]:
from torchinfo import summary

summary(model,input_size=(10,5))
#

Layer (type:depth-idx)                   Output Shape              Param #
NNModel                                  [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#Train the same Breast Cancer Model using NN Module to improve results

In [26]:
class SimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
  def forward(self,features):
    out=self.network(features)
    return out


loss_function=nn.BCELoss()



In [24]:
epochs=50

In [35]:
model=SimpleNN(X_train_tensor.shape[1])
optimizer=optim.Adam( model.parameters(),lr=0.1)
X_train_tensor = X_train_tensor.type(torch.float32)
y_train_tensor = y_train_tensor.type(torch.float32)
for epoch in range(epochs):
  y_pred=model(X_train_tensor)
  loss=loss_function(y_pred,y_train_tensor.view(-1,1))
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")


Epoch: 1, Loss: 0.7651242017745972
Epoch: 2, Loss: 0.4771151840686798
Epoch: 3, Loss: 0.33630576729774475
Epoch: 4, Loss: 0.2735133171081543
Epoch: 5, Loss: 0.2217736542224884
Epoch: 6, Loss: 0.17470261454582214
Epoch: 7, Loss: 0.14104798436164856
Epoch: 8, Loss: 0.11923261731863022
Epoch: 9, Loss: 0.1040579304099083
Epoch: 10, Loss: 0.0930393859744072
Epoch: 11, Loss: 0.08570439368486404
Epoch: 12, Loss: 0.08145307749509811
Epoch: 13, Loss: 0.07873011380434036
Epoch: 14, Loss: 0.07573136687278748
Epoch: 15, Loss: 0.07292080670595169
Epoch: 16, Loss: 0.07091082632541656
Epoch: 17, Loss: 0.0684184730052948
Epoch: 18, Loss: 0.06596551090478897
Epoch: 19, Loss: 0.06384851783514023
Epoch: 20, Loss: 0.062079235911369324
Epoch: 21, Loss: 0.06036974862217903
Epoch: 22, Loss: 0.058637894690036774
Epoch: 23, Loss: 0.05690719559788704
Epoch: 24, Loss: 0.055340953171253204
Epoch: 25, Loss: 0.05401754006743431
Epoch: 26, Loss: 0.05264456197619438
Epoch: 27, Loss: 0.050836797803640366
Epoch: 28, Lo

In [36]:
#model evaluation
X_test_tensor=X_test_tensor.type(torch.float32)
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5220067501068115
