<a href="https://colab.research.google.com/github/shachimaurya23/Learning/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import torch and check for GPU

In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
using GPU: Tesla T4


# Creating a Tensor

In [ ]:
 # using empty
a=torch.empty(2,3)

In [ ]:
#check type
type(a )

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.1883, 0.8403, 0.4258],
        [0.0997, 0.7505, 0.7697]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using Tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways
#arange
print("arange-> ",torch.arange(0,10))

#linspace
print("linspace->",torch.linspace(0,10,10))

#eye
print("eye->",torch.eye(5))

#full
print("full->",torch.full((3,3),5))

arange->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    135832832687504,           150965840,                   0],
        [                  0,                   0, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x.to(torch.float32))

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [ ]:
#find datatype
x.dtype

torch.int64

In [ ]:
#assign a data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# change data type of tensor
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical operations

## Scaler Operations

In [ ]:
x=torch.rand(2,2)

In [ ]:
2+x

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [ ]:
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [ ]:
x*2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [ ]:
x/2

tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])

In [ ]:
(x*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [ ]:
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

In [ ]:
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

## Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

In [ ]:
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [ ]:
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [ ]:
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [ ]:
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [ ]:
a**b

tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])

In [ ]:
a%b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d,2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])