<a href="https://colab.research.google.com/github/shachimaurya23/Learning/blob/main/Pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import torch and check for GPU

In [2]:
import torch
print(torch.__version__)

2.5.1+cu121


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
using GPU: Tesla T4


# Creating a Tensor

In [ ]:
 # using empty
a=torch.empty(2,3)

In [ ]:
#check type
type(a )

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.1883, 0.8403, 0.4258],
        [0.0997, 0.7505, 0.7697]])

In [ ]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using Tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways
#arange
print("arange-> ",torch.arange(0,10))

#linspace
print("linspace->",torch.linspace(0,10,10))

#eye
print("eye->",torch.eye(5))

#full
print("full->",torch.full((3,3),5))

arange->  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
linspace-> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[    135832832687504,           150965840,                   0],
        [                  0,                   0, 7310593858020254331]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x.to(torch.float32))

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# Tensor Data Types

In [ ]:
#find datatype
x.dtype

torch.int64

In [ ]:
#assign a data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
# change data type of tensor
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

# Mathematical operations

## Scaler Operations

In [ ]:
x=torch.rand(2,2)
2+x
x-2
x*2
x/2
(x*100)//3
((x*100)//3)%2
x**2

## Element wise operation

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
a+b
a-b
a*b
a/b
a**b
a%b
c=torch.tensor([1,-2,3,-4])
torch.abs(c)
torch.neg(c)
d=torch.tensor([1.9,2.3,3.7,4.4])
torch.round(d)
torch.ceil(d)
torch.floor(d)
torch.clamp(d,2,3)# produces VALUES IN RANGE 2 AND 3 FROMTHE TENSOR VALUES

## Reduction Operations

In [4]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e
torch.sum(e)
#sum on col
torch.sum(e,dim=0)
#sum on row
torch.sum(e,dim=1)
torch.mean(e)
#mean on col
torch.mean(e,dim=0)
torch.median(e)
torch.std(e)
torch.var(e)
torch.argmin(e)# pos of min
torch.argmax(e)# pos of max
torch.max(e)
torch.min(e)

## Matrix Operations

In [19]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [20]:
print(f,g)

tensor([[4, 7, 0],
        [2, 0, 2]]) tensor([[4, 7],
        [7, 5],
        [0, 8]])


In [21]:
torch.matmul(f,g) #matrix multiply

tensor([[65, 63],
        [ 8, 30]])

In [22]:
vec1=torch.tensor([1,2])
vec2=torch.tensor([2,3])

In [23]:
torch.dot(vec1,vec2)#dot product

tensor(8)

In [26]:
f

tensor([[4, 7, 0],
        [2, 0, 2]])

In [25]:
#transpose
torch.transpose(f,dim0=0,dim1=1)

tensor([[4, 2],
        [7, 0],
        [0, 2]])

In [29]:
#determinant
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(h)

tensor(208.0000)

In [31]:
#inverse
torch.inverse(h)

tensor([[ 0.1971, -0.1202, -0.0240],
        [ 0.0192,  0.1346, -0.1731],
        [-0.1346,  0.0577,  0.2115]])

## Comparison Operations

In [32]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 3, 7],
        [2, 1, 2]])
tensor([[9, 8, 4],
        [3, 3, 6]])


In [37]:
i>j
i<j
i==j
i!=j
i<=j
i>=j

tensor([[False, False,  True],
        [False, False, False]])

## Special Functions

In [45]:
k=torch.randint(size=(2,3), low=0, high=10,dtype=torch.float32)
k

tensor([[7., 1., 3.],
        [0., 5., 4.]])

In [41]:
#log
torch.log(k)

tensor([[0.0000,   -inf, 1.6094],
        [0.0000, 2.0794, 1.0986]])

In [42]:
#exponent
torch.exp(k)

tensor([[2.7183e+00, 1.0000e+00, 1.4841e+02],
        [2.7183e+00, 2.9810e+03, 2.0086e+01]])

In [43]:
#sqrt
torch.sqrt(k)

tensor([[1.0000, 0.0000, 2.2361],
        [1.0000, 2.8284, 1.7321]])

In [44]:
#sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.5000, 0.9933],
        [0.7311, 0.9997, 0.9526]])

In [46]:
#softmax but need to provide dim
torch.softmax(k,dim=0)

tensor([[9.9909e-01, 1.7986e-02, 2.6894e-01],
        [9.1105e-04, 9.8201e-01, 7.3106e-01]])

In [47]:
# relu
torch.relu(k)

tensor([[7., 1., 3.],
        [0., 5., 4.]])

# Inplace Operations

In [48]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [49]:
print(m,n)

tensor([[0.5552, 0.4312, 0.6440],
        [0.6978, 0.6240, 0.7400]]) tensor([[0.2748, 0.7076, 0.8419],
        [0.5474, 0.8385, 0.9993]])


In [50]:
m.add_(n)

tensor([[0.8300, 1.1388, 1.4859],
        [1.2452, 1.4625, 1.7394]])

In [51]:
print(m)
print(n)

tensor([[0.8300, 1.1388, 1.4859],
        [1.2452, 1.4625, 1.7394]])
tensor([[0.2748, 0.7076, 0.8419],
        [0.5474, 0.8385, 0.9993]])


In [52]:
m.relu_()

tensor([[0.8300, 1.1388, 1.4859],
        [1.2452, 1.4625, 1.7394]])

# Copying tensor

In [53]:
a=torch.rand(2,3)

In [55]:
a

tensor([[0.3457, 0.0106, 0.3341],
        [0.0392, 0.4745, 0.7478]])

In [54]:
b=a

In [56]:
b

tensor([[0.3457, 0.0106, 0.3341],
        [0.0392, 0.4745, 0.7478]])

In [62]:
a[0][0]=0
a

tensor([[0.0000, 0.0000, 0.3341],
        [0.0392, 0.4745, 0.7478]])

In [63]:
b

tensor([[0.3457, 0.0000, 0.3341],
        [0.0392, 0.4745, 0.7478]])

In [59]:
print(id(a),id(b))

139305374688720 139305374688720


In [60]:
b=a.clone()

In [61]:
print(id(a),id(b))

139305374688720 139303656668720


# tensor operations on GPU

In [64]:
torch.cuda.is_available()

True

In [65]:
device=torch.device("cuda")

In [66]:
torch.rand((2,3),device=device)

tensor([[0.3589, 0.6131, 0.1427],
        [0.5901, 0.9966, 0.9011]], device='cuda:0')

In [68]:
b=b.to(device)

In [69]:
b+5

tensor([[5.3457, 5.0000, 5.3341],
        [5.0392, 5.4745, 5.7478]], device='cuda:0')

# Speed Testing between GPU and CPU

In [2]:
import time
import torch
size=10000

mat1=torch.randn(size,size)
mat2=torch.randn(size,size)

start_time=time.time()
matmul_cpu=torch.matmul(mat1,mat2)
cpu_time=time.time()-start_time
print(f"time on cpu computation {cpu_time:.4f} seconds")

mat1_gpu=mat1.to('cuda')
mat2_gpu=mat2.to('cuda')


start_time=time.time()
matmul_gpu=torch.matmul(mat1_gpu,mat2_gpu)
torch.cuda.synchronize() # ensures all GPU operations are complete
gpu_time=time.time()-start_time
print(f"time on gpu computation {gpu_time:.4f} seconds")

print(f"speed cpu/gpu:{cpu_time/gpu_time}")

time on cpu computation 27.7506 seconds
time on gpu computation 0.6472 seconds
speed cpu/gpu:42.87648720829573


# Reshape Tensors

In [4]:
f=torch.ones(4,4)
f

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
#reshape
f.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [8]:
f.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
b=torch.rand(2,3,4)
b

tensor([[[0.2495, 0.8688, 0.8550, 0.2591],
         [0.0545, 0.5846, 0.1809, 0.3147],
         [0.1722, 0.0835, 0.5408, 0.9815]],

        [[0.2730, 0.4964, 0.6230, 0.6100],
         [0.6701, 0.7923, 0.1337, 0.3732],
         [0.3123, 0.9360, 0.7187, 0.9645]]])

In [12]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [14]:
#unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(dim=1).shape # adds new dim can be helpful to convert one image to batch for 4d tensor

torch.Size([226, 1, 226, 3])

In [18]:
#squeeze
d=torch.rand(23,20,1)
d.squeeze(2).shape

torch.Size([23, 20])

# Numpy and Pytorch

In [19]:
import numpy as np

In [20]:
a=torch.tensor([1,2,3])

In [21]:
b=a.numpy()

In [22]:
b

array([1, 2, 3])

In [23]:
c=np.array([1,2,3])

In [24]:
torch.from_numpy(c)

tensor([1, 2, 3])