<a href="https://colab.research.google.com/github/shachimaurya23/Learning/blob/main/PyTorch/Pytorch_learning_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Autograd for y=x**2

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
y=x**2

In [ ]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


In [ ]:
y.backward()
x.grad

tensor(6.)

# Autograd for z=sin(y)

In [ ]:
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
y=x**2

In [ ]:
z=torch.sin(y)

In [ ]:
print(x,y,z)

tensor(3., requires_grad=True) tensor(9., grad_fn=<PowBackward0>) tensor(0.4121, grad_fn=<SinBackward0>)


In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

# Autograd on Perceptron Neural Network

In [2]:
x=torch.tensor(6.7) #input feature
y=torch.tensor(0.0) #binary label

w=torch.tensor(1.0) #weight
b=torch.tensor(0.0) #bias

In [3]:
#binary cross entropy loss for scalar
def binary_cross_entropy_loss(pred,target):
  epsilon=1e-8 # to prevent log(0)
  pred=torch.clamp(pred,epsilon,1-epsilon)
  return -(target*torch.log(pred)+(1-target)*torch.log(1-pred))

In [4]:
#Forward pass
z=w*x+b #weighted sum
y_pred=torch.sigmoid(z) # probability predicted
loss=binary_cross_entropy_loss(y_pred,y) #loss calcuated

In [5]:
loss

tensor(6.7012)

In [6]:
# Derivatives:
# 1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

# 2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred * (1 - y_pred)

# 3. dz/dw and dz/db: z with respect to w and b
dz_dw = x  # dz/dw = x
dz_db = 1  # dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db
print(f"Manual Gradient of loss w.r.t weight (dw): {dL_dw}")
print(f"Manual Gradient of loss w.r.t bias (db): {dL_db}")

Manual Gradient of loss w.r.t weight (dw): 6.691762447357178
Manual Gradient of loss w.r.t bias (db): 0.998770534992218


In [7]:
x=torch.tensor(6.7) #input feature
y=torch.tensor(0.0) #binary label

w=torch.tensor(1.0,requires_grad=True) #weight
b=torch.tensor(0.0,requires_grad=True) #bias

In [8]:
#Forward pass
z=w*x+b #weighted sum
y_pred=torch.sigmoid(z) # probability predicted
loss=binary_cross_entropy_loss(y_pred,y) #loss calcuated

In [9]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [10]:
# backward propogation
loss.backward()

In [11]:
w.grad

tensor(6.6918)

In [12]:
b.grad

tensor(0.9988)

# Autograd on vector input tensor

In [26]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)

In [27]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [28]:
y.backward()

In [29]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [18]:
#clearing grad to prevent from adding previous grad
x.grad.zero_()

tensor([0., 0., 0.])

In [30]:
#disable grad when using prediction after training as it requires a lot of memeory so we disable backward tracking

#option 1 requires_grad=False
x.requires_grad_(False)
#option 2 detach()
z=x.detach()
#option 3 torch.no_grad()
with torch.no_grad():
  y=x**2
y

tensor([1., 4., 9.])

In [25]:
z

tensor([1., 2., 3.])